version: "3.8"

services: 
    db:
        image: postgres:12
        environment:
            POSTGRES_PASSWORD: 63eaQB9wtLqmNBpg
            POSTGRES_DB: api
    api:
        build: .
        command: npm run dev
        volumes: 
            - /usr/app/node_modules
            - ./:/usr/app
        ports: 
            - 3000:3000
        environment: 
            - DB_CONNECTION=pg
            - DB_HOST=db
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_DATABASE=api
            - DB_PASSWORD=63eaQB9wtLqmNBpg